---
name: httpd
director_uuid: 63ddb6a6-d6fe-40e1-b16b-2ff6b2034c79

releases:
- name: httpd
  version: latest

networks:
- name: default
  subnets:
  - range: 10.244.0.0/28
    reserved: [10.244.0.3]
    static: [10.244.0.4,10.244.0.5,10.244.0.7]
    cloud_properties:
      name: random

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

compilation:
  workers: 2
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: httpd
  templates:
  - name: httpd
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.0.4
  properties: {}
